name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    name: Install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Install bundletool
        run: wget https://github.com/google/bundletool/releases/download/1.10.0/bundletool-all-1.10.0.jar && ls && java --version
      - name: Build on local
        run: npm i -g eas-cli && eas build --platform android --local && ls
      - name: generate apk file
        run: java -jar bundletool-all-1.10.0.jar build-apks --mode=universal --bundle=$(ls | grep "\.aab") --output=jeff-tian.apks&&java -jar bundletool-all-1.10.0.jar install-apks --apks=jeff-tian.apks&&ls
      - name: generate release key
        run: echo -n ${{secrets.MY_RELEASE_KEY}} | base64 --decode > my-release-key.jks && ls
      - name: zipalign
        run: zipalign -v -p 4 universal.apk jeff-tian-unsigned-aligned.apk
      - name: sign apk
        run: echo ${{ secrets.RELEASE_KEY_PASSWORD }} | apksigner sign --ks my-release-key.jks --out jeff-tian-release.apk jeff-tian-unsigned-aligned.apk
      - name: Build on EAS
        run: eas build --platform android --non-interactive